title: xAI Lab, University of Marburg, Germany
logo: "/assets/images/xai-logo.svg"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Chair for Artificial Intelligence at the Philipps-University Marburg and hessian.ai.
twitter_username: SeifertChristin
github_username: mcmi-group
minimal_mistakes_skin: contrast
search: true
# Build settings
markdown: kramdown
#remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll 

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
# misusing author field for group info
  name   : "xAI Lab"
#  avatar : "/assets/images/people/Seifert-Christin.jpg"
  bio    : "University of Marburg<br>Hans-Meerwein-Straße 6<br>35043 Marburg<br>Germany"
  links:
    - label: "Uni Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.uni-marburg.de/en/fb12/research-groups/artificial-intelligence-explainable-ai"
    - label: "Department"
      icon: "fas fa-fw fa-link"
      url: "https://www.uni-marburg.de/en/fb12"
    - label: "Personal Website"
      icon: "fas fa-fw fa-link"
      url: "http://christinseifert.info"
    - label: "hessian.ai"
      icon: "fas fa-fw fa-link"
      url: "https://hessian.ai"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mcmi-group"

footer:
  links:
    - label: "Department"
      icon: "fas fa-fw fa-link"
      url: "https://www.uni-marburg.de/en/fb12"
    - label: "hessian.ai"
      icon: "fas fa-fw fa-link"
      url: "https://hessian.ai"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mcmi-group"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# configure scholar plugin
plugins: ['jekyll/scholar']
scholar:
  source: /_bibliography
  style: ieee
  group_by: year
  group_order: descending
  sort_by: year,month
  order: descending
  bibliography_template: bib

# ignore deprecation warnings  
sass:
  quiet_deps: true
